spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    url: jdbc:mysql://localhost:3307/screener?allowPublicKeyRetrieval=true
    username: root
    password: j&4$R>TqA2

ru:
  tinkoff:
    piapi:
      core:
        target: invest-public-api.tinkoff.ru:443
        connection-timeout: 5
        request-timeout: 5
        token: ${COMMON_TOKEN}
  coin-market-cap:
    url: https://pro-api.coinmarketcap.com/v1/cryptocurrency
    token: ${COIN_MARKET_CAP_TOKEN}
  twelve-data:
    url: https://api.twelvedata.com
    token: ${TWELVE_DATA_TOKEN}
logging:
  level:
    root: ${LOGGING_LEVEL}
service:
  crypto:
    daily-cron: ${CRYPTO_PRICES_CRON}
  tinkoff:
    instruments: ${INSTRUMENTS}
    daily-cron: ${CRON}
  telegram:
    bot:
      url: ${TELEGRAM_NOTIFICATION_BOT_URL}
      admin-account: ${ADMIN_ACCOUNT}
      accounts:
        - ${ACCOUNT_ID_ONE}