server:
  shutdown: graceful

spring:
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: screener
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    url: jdbc:mysql://localhost:3307/screener?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: j&4$R>TqA2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      client-name: screener-app
      client-type: lettuce
  cache:
    type: redis
    redis:
      cache-null-values: false

ru:
  tinkoff:
    piapi:
      core:
        target: invest-public-api.tinkoff.ru:443
        connection-timeout: PT30
        request-timeout: PT30
        token: t.z3VkhlabQQqBM7v2JRuRcOLB9tWDluDgpz24p1yo38BQbS6VqGH4bYBPw0ORrL35qXjKk4Cwk4NEwxh0sT1mcQ
  coin-market-cap:
    url: https://pro-api.coinmarketcap.com/v1/cryptocurrency
    token: 6829f0ff-56e0-48f8-8cc2-11dcc37cc9f3
  twelve-data:
    url: https://api.twelvedata.com
    token:
      - b7e76a8b950e427daafdf6d939e4dd82
      - 45cdc790f12540cabc0efdfa07e799dc
      - 65901c0f82324bdc84816468b2aa0838
      - a37067dc3b4642f8aabe9b26627ea960
      - 16ecacf18e744e8099ff2052e851d160
  trading:
    service:
      url: trading-bot:9091
logging:
  level:
    root: debug
service:
  crypto:
    daily-cron: 0 35 23 * * MON-FRI
    prices-cron: 0 35 23 * * MON-FRI
    instruments: BTC/USD,ETH/USD,BNB/USD,SOL/USD,DOGE/USD,XRP/USD,ADA/USD,TON/USD,SHIB/USD,DOT/USD,AVAX/USD,LINK/USD,TRX/USD,MATIC/USD,NEAR/USD,ICP/USD,UNI/USD,LTC/USD,APT/USD,DAI/USD,ETC/USD,STX/USD,FIL/USD,MNT/USD,ATOM/USD,ARB/USD,CRO/USD,XLM/USD,IMX/USD,RNDR/USD,HBAR/USD,OKB/USD,VET/USD,KAS/USD,MKR/USD,INJ/USD,OP/USD,GRT/USD,PEPE/USD,THETA/USD,FTM/USD,XMR/USD,RUNE/USD,LDO/USD,FET/USD,AR/USD,SUI/USD,CORE/USD,TIA/USD,ALGO/USD,AAVE/USD,FLOW/USD,GALA/USD,BSV/USD,BEAM/USD,EGLD/USD,BTT/USD,DYDX/USD,XEC/USD,AXS/USD,SAND/USD,QNT/USD,STRK/USD,NEO/USD,CHZ/USD,SEI/USD,SNX/USD,XTZ/USD,EOS/USD,WLD/USD,CFX/USD,PYTH/USD,RON/USD,MANA/USD,ONDO/USD,KAVA/USD,JASMY/USD,APE/USD,KCS/USD,IOTA/USD,MINA/USD
  tinkoff:
    instruments: BBG004731489,BBG004730N88
    daily-cron: 0 35 23 * * MON-FRI
  telegram:
    bot:
      url: localhost:9091
      admin-account: 501710552
      accounts:
        - 2199915782